In [ ]:
#Task-1
class PlayerEarning:
  def __init__(self,name):
    self.name = name
  def calculateTotal(self,salary,goal = 0):
    self.salary = salary
    self.bonus = 0
    if goal>30:
      self.bonus = (5/100)*self.salary+10000
    elif goal == 0:
      self.bonus = 0
    else:
      self.bonus = (5/100)*self.salary

  def printDetails(self):
    print(f"Player Name: {self.name}")
    print(f"Player Season Earning without bonus: {int(self.salary)}")
    print(f"Bonus: {int(self.bonus)}")


print("**********************")
player1 = PlayerEarning('Buffon')
player1.calculateTotal(250000)
player1.printDetails()

print("\n**********************")
player2 = PlayerEarning('Dybala')
player2.calculateTotal(250000, 31)
player2.printDetails()

print("\n**********************")
player3 = PlayerEarning('Cuadrado')
player3.calculateTotal(250000, 20)
player3.printDetails()

**********************
Player Name: Buffon
Player Season Earning without bonus: 250000
Bonus: 0

**********************
Player Name: Dybala
Player Season Earning without bonus: 250000
Bonus: 22500

**********************
Player Name: Cuadrado
Player Season Earning without bonus: 250000
Bonus: 12500

In [ ]:
#Task-2
class myList:
  def __init__(self,*args):
    self.a_list = []
    for i in args:
      self.a_list.append(i)
  def sum(self):
    sum = 0
    for j in self.a_list:
      sum+=j
    print(f"Sum: {sum}")
  def merge(self,*args):
    for i in args:
      self.a_list.append(i)
  def average(self):
    sum = 0
    for k in self.a_list:
      sum+=k
    if sum ==0:
      print(f"Average: {sum}")
    else:
      print(f"Average: {sum/len(self.a_list)}")

l1 =  myList(2,3,4,5,6)
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print("-----------------------------")
l2 =  myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

Sum: 20
Sum: 38
Average: 4.75
-----------------------------
Average: 0
Sum: 15

In [ ]:
#Task-3
class Bird:
  def __init__(self,name,x = False):
    self.name = name
    self.x = x
    self.typ = "Flightless Birds"
  def fly(self):
    if self.x == False:
      print(f"{self.name} can not fly")
    else:
      print(f"{self.name} can fly")
  def setType(self,typ = "Flightless Birds"):
    self.typ = typ
  def printDetail(self):
    print(f"Name: {self.name}\nType: {self.typ}")
ostrich = Bird('Ostrich')
duck = Bird("Duck", True)
owl = Bird('Owl', True)
print("###########################")
ostrich.fly()
duck.fly()
owl.fly()
duck.setType('Water Birds')
owl.setType('Birds of Prey')
print("=========================")
ostrich.printDetail()
print('=========================')
duck.printDetail()
print("=========================")
owl.printDetail()

###########################
Ostrich can not fly
Duck can fly
Owl can fly
=========================
Name: Ostrich
Type: Flightless Birds
=========================
Name: Duck
Type: Water Birds
=========================
Name: Owl
Type: Birds of Prey

In [ ]:
#Task-4
class Account:
  count = 0
  def __init__(self,name,age,occ,amount):
    self.name = name
    self.age = age
    self.occ = occ
    self.amount = amount
    Account.count+=1
  def addMoney(self,x):
    self.amount+=x
  def withdrawMoney(self,y):
    if y>self.amount:
        self.amount = self.amount
  def printDetails(self):
    print(f"Name: {self.name}\nAge: {self.age}\nOccupation: {self.occ}\nTotal Amount: {self.amount}")
print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================")
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name: Abdul
Age: 45
Occupation: Service Holder
Total Amount: 800000
=========================
Name: Rahim
Age: 55
Occupation: Businessman
Total Amount: 700000
=========================
Name: Ashraf
Age: 62
Occupation: Govt. Officer
Total Amount: 200000
=========================
No of account holders: 3

In [ ]:
#Task-5
class Smartphone:
  def __init__(self,name=""):
    self.name = name
    self.a_dict = {}
  def setName(self,name):
    self.name = name
  def addFeature(self,x,y):
    if self.name =="":
      print("Feature can not be added without phone name")
    else:
      if x not in self.a_dict:
        self.a_dict[x] = [y]
      else:
        self.a_dict[x].append(y)
  def printDetail(self):
    print(f"Phone Name: {self.name}")
    for key,value in self.a_dict.items():
      a = ",".join(value)
      print(f"{key}:{a}")


s1 = Smartphone()
print("=================================")
s1.addFeature("Display", "6.1 inch")
print("=================================")
s1.setName("Samsung Note 20")
s1.addFeature("Display", "6.1 inch")
s1.printDetail()
print("=================================")
s2 = Smartphone("Iphone 12 Pro")
s2.addFeature("Display", "6.2 inch")
s2.addFeature("Ram", "6 GB")
print("=================================")
s2.printDetail()
s2.addFeature("Display", "Amoled panel")
s2.addFeature("Ram", "DDR5")
print("=================================")
s2.printDetail()
print("=================================")

=================================
Feature can not be added without phone name
=================================
Phone Name: Samsung Note 20
Display:6.1 inch
=================================
=================================
Phone Name: Iphone 12 Pro
Display:6.2 inch
Ram:6 GB
=================================
Phone Name: Iphone 12 Pro
Display:6.2 inch,Amoled panel
Ram:6 GB,DDR5
=================================

In [ ]:
#Task-6
class Student:
  count = 0
  cse = 0
  bba = 0
  def __init__(self,name,dept):
    self.name = name
    self.dept = dept
    if self.dept == "CSE":
      Student.cse+=1
    else:
      Student.bba+=1
    Student.count+=1
    print(f"Creating student Number: {Student.count}")
  def individualInfo(self):
    print(f"{self.name} is from {self.dept} department.")
    print(f"Serial of {self.name} among all students' is: {Student.count}")
    if self.dept =="CSE":
      print(f"Serial of {self.name} in {self.dept} department is: {Student.cse}")
    else:
      print(f"Serial of {self.name} in {self.dept } department is: {Student.bba}")
  def totalInfo(self):
    print(f"Total Number of Student: {Student.count}")
    print(f"Total Number of {self.dept} Student: {Student.cse}")
    print(f"Total Number of {self.dept} Student: {Student.bba}")
s1 = Student("Naruto", "CSE")
print('----------------------')
s1.individualInfo()
print('#############################')
s1.totalInfo()
print('============================')


s2 = Student("Sakura", "BBA")
print('----------------------')
s2.individualInfo()
print('#############################')
s2.totalInfo()
print('============================')


s3 = Student("Shikamaru", "CSE")
print('----------------------')
s3.individualInfo()
print('#############################')
s3.totalInfo()
print('============================')


s4 = Student("Deidara", "BBA")
print('----------------------')
s4.individualInfo()
print('#############################')
s4.totalInfo()

Creating student Number: 1
----------------------
Naruto is from CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student: 1
Total Number of CSE Student: 1
Total Number of CSE Student: 0
============================
Creating student Number: 2
----------------------
Sakura is from BBA department.
Serial of Sakura among all students' is: 2
Serial of Sakura in BBA department is: 1
#############################
Total Number of Student: 2
Total Number of BBA Student: 1
Total Number of BBA Student: 1
============================
Creating student Number: 3
----------------------
Shikamaru is from CSE department.
Serial of Shikamaru among all students' is: 3
Serial of Shikamaru in CSE department is: 2
#############################
Total Number of Student: 3
Total Number of CSE Student: 2
Total Number of CSE Student: 1
============================
Creating student Number: 4
----------------------
Deidara is from BBA department.
Serial of Deidara among all students' is: 4
Serial of Deidara in BBA department is: 2
#############################
Total Number of Student: 4
Total Number of BBA Student: 2
Total Number of BBA Student: 2

In [ ]:
#Task-7
class book:
    def __init__(self, name):
        self.name = name
        self.genre='biography'
    def review(self):
         print('This book is just out of the world,mind-blowing!')
class fiction(book):
  def __init__(self,name,typ):
    super().__init__(name)
    self.genre = typ
  def review(self):
    print(f"{self.name} Which is a {self.genre} is just out of the world, mind-blowing! ")
class nonfiction(book):
  def __init__(self,name):
    super().__init__(name)
  def review(self):
    print(f"{self.name} Which is a {self.genre} is just out of the world, mind-blowing! ")



# Write your code here

b1 = fiction('The Shining','Psychological horror')
b2 = nonfiction('A Beautiful Mind')
b1.review()
print('=========================')
b2.review()
print('=========================')

The Shining Which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind Which is a biography is just out of the world, mind-blowing!
=========================

In [ ]:
#Task-8
class Processor:
    def __init__(self, model, thread, core):
        self.model = model
        self.core = core
        self.thread = thread
    def getInfo(self):
        return "Model:"+self.model+ "\nCores:"+str(self.core)+ "\nThreads:"+ str(self.thread)
class Intel(Processor):
  def __init__(self,model,thread,core,price):
    super().__init__(model,thread,core)
    self.price = price
  def getInfo(self):
    s = super().getInfo()
    print(f"{s}\nprice: {self.price}")
class AMD(Processor):
  def __init__(self,model,thread,core,price):
    super().__init__(model,thread,core)
    self.price = price
  def getInfo(self):
    s = super().getInfo()
    print(f"{s}\nprice: {self.price}")

p1 = Intel("Intel i5 10th Gen",6,12,17000)
p2 = AMD("Ryzen 5 3500X",6,6,13800)
p3 = AMD("Ryzen 5 3600",6,12,16900)
print('======================')
p1.getInfo()
print('======================')
p2.getInfo()
print('======================')
p3.getInfo()

======================
Model:Intel i5 10th Gen
Cores:12
Threads:6
price: 17000
======================
Model:Ryzen 5 3500X
Cores:6
Threads:6
price: 13800
======================
Model:Ryzen 5 3600
Cores:12
Threads:6
price: 16900

In [ ]:
#Task-9
class Fruit:
    Total_order=0

    def __init__(self, Order_ID, weight):
        self.Order_ID=Order_ID
        self.weight=weight
        Fruit.Total_order=Fruit.Total_order+1

    def __str__(self):
        return self.Order_ID+", Weight: "+str(self.weight)

class Mango(Fruit):
  def __init__(self,id,weight,typ,price):
    super().__init__(id,weight)
    self.typ = typ
    self.price = price
  def __str__(self):
    s = super().__str__()
    s+=f', Variety: {self.typ},\nTotal Price: {self.weight*self.price}'
    return s
  def __add__(self,other):
    if isinstance(other,Mango):
      return f"The total Price of the orders are: {self.weight*self.price+(other.weight*other.price)}"
class JackFruit(Fruit):
  def __init__(self,id,weight,price):
    super().__init__(id,weight)
    self.price = price
  def __str__(self):
    s = super().__str__()
    s+=f",Total Price: {self.price*self.weight}"
    return s
  def __add__(self,other):
    if isinstance(other,JackFruit):
      return f"The total Price of the orders are: {self.weight*self.price+(other.weight*other.price)}"


m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2)
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5, Variety: GopalVog,
Total Price: 1250
Order Id 2, Weight: 5, Variety: HariVanga,
Total Price: 1150
Order Id 3, Weight: 5,Total Price: 1250
Order Id 4, Weight: 4,Total Price: 840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

In [ ]:
#Task-10
class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"
class CSEStudent(Student):
  def __init__(self,name,id,session):
    super().__init__(name,id)
    self.session = session
    self.a_dict = {}
  def Details(self):
    s = super().Details()
    s+=f"Current Semester: {self.session}"
    return s
  @staticmethod
  def grade(mark):
    if mark>=85:
      return "4.0"
    elif 80<=mark<=84:
      return "3.3"
    elif 70<=mark<=79:
      return "3.0"
    elif 65<=mark<=69:
      return "2.3"
    elif 57<=mark<=64:
      return 2.0
    elif 55<=mark<=56:
      return "1.3"
    elif 50<=mark<=54:
      return "1.0"
    else:
      return "0.0"

  def addCourseWithMarks(self,*args):#("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
    for i in range(0,len(args),2):
          self.a_dict[args[i]] = CSEStudent.grade(args[i+1])
  def showGPA(self):
    print(f"Bob has taken {len(self.a_dict)} Courses.")
    sum = 0
    for key,value in self.a_dict.items():
      sum+= float(value)
      print(f"{key}: {value}")
    print(f"CGPA of Bob is {sum/len(self.a_dict)}")

Bob = CSEStudent("Bob","20301018","Fall 2020")
Carol = CSEStudent("Carol","16301814","Fall 2020")
Anny = CSEStudent("Anny","18201234","Fall 2020")
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current Semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current Semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current Semester: Fall 2020
#########################
----------------------------
Bob has taken 3 Courses.
CSE111: 3.3
CSE230: 3.0
CSE260: 4.0
CGPA of Bob is 3.4333333333333336
----------------------------
Bob has taken 4 Courses.
CSE470: 2.0
CSE422: 2.3
CSE460: 3.0
CSE461: 4.0
CGPA of Bob is 2.825
----------------------------
Bob has taken 3 Courses.
CSE340: 0.0
CSE321: 4.0
CSE370: 4.0
CGPA of Bob is 2.6666666666666665

In [ ]:
#Task-11
class Transport:
    total_traveller = 0

    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare

    def __str__(self):
        s =  "Name: "+self.name+", Base fare: "+str(self.baseFare)
        return s
class Bus(Transport):
  def __init__(self,name,fare):
    super().__init__(name,fare)
    self.a_dict = {}
    Transport.total_traveller+=len(self.a_dict)
    print(f"Base-fare of {self.name} is {self.baseFare} Taka")
  def addPassengerWithBags(self,*args):
    for i in range(0,len(args),2):
      if i not in self.a_dict:
        if args[i+1]>=3 and args[i+1]<=5:
          self.a_dict[args[i]] = self.baseFare+60
        elif args[i+1]>5:
          self.a_dict[args[i]] = self.baseFare+105
        else:
          self.a_dict[args[i]] = self.baseFare
    Transport.total_traveller+=len(self.a_dict)
  def __str__(self):
    s = super().__str__()
    s+= f"\nTotal Passengers: {len(self.a_dict)}"
    s+="\nPasserger details:"
    for key,value in self.a_dict.items():
         s+= f"\nName: {key},Fare: {value}"
    return s
class Train(Transport):
  def __init__(self,name,fare):
    super().__init__(name,fare)
    self.a_dict = {}
    print(f"Base-fare of {self.name} is {self.baseFare} Taka")
  def addPassengerWithBags(self,*args):
    for i in range(0,len(args),2):
      if i not in self.a_dict:
        if args[i+1]>=3 and args[i+1]<=5:
          self.a_dict[args[i]] = self.baseFare+60
        elif args[i+1]>5:
          self.a_dict[args[i]] = self.baseFare+105
        else:
          self.a_dict[args[i]] = self.baseFare
    Transport.total_traveller+=len(self.a_dict)
  def __str__(self):
    s = super().__str__()
    s+= f"\nTotal Passengers: {len(self.a_dict)}"
    s+="\nPasserger details:"
    for key,value in self.a_dict.items():
         s+= f"\nName: {key},Fare: {value}"
    return s
t1 = Bus("Volvo", 950)
print("=================================")
t1.addPassengerWithBags("David", 6,  "Mike", 1, "Carol", 3)
print("=================================")
print(t1)
print("=================================")
t2 = Train("Silk City", 850)
print("=================================")
t2.addPassengerWithBags("Bob", 2, "Simon", 4)
print("=================================")
print(t2)
print("=================================")
print("Total Passengers in Transport: ", Transport.total_traveller )

Base-fare of Volvo is 950 Taka
=================================
=================================
Name: Volvo, Base fare: 950
Total Passengers: 3
Passerger details:
Name: David,Fare: 1055
Name: Mike,Fare: 950
Name: Carol,Fare: 1010
=================================
Base-fare of Silk City is 850 Taka
=================================
=================================
Name: Silk City, Base fare: 850
Total Passengers: 2
Passerger details:
Name: Bob,Fare: 850
Name: Simon,Fare: 910
=================================
Total Passengers in Transport:  5

In [ ]:
#Task-12
class AppleProduct:
  def __init__(self, name, model, base_price):
    self.name = name
    self.model = model
    self.base_price = base_price
  def companyInfo(self):
    st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States")
    return st
  def feature(self):
    st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
    return st
  def __str__(self):
    print('This is apple product.')
  def calculatePrice(self):
    print('Total Price:', self.base_price)
class MacBookPro2020(AppleProduct):
  def __init__(self,name,model,ram,chip,perc,x = 1299):
    super().__init__(name,model,x)
    self.ram = ram
    self.chip = chip
    self.perc = perc
  def __str__(self):
    s = super().feature()
    s+= f"\nRAM: {self.ram}GB"
    s+=f"\nChip: {self.chip}"
    s+= f"\n{super().companyInfo()}"
    return s
  def calculatePrice(self):
    print("Calculating Price")
    print(f"Base price: {self.base_price}\nTax: {self.perc}%\nTotal Price: {self.base_price + self.base_price*(self.perc/100)}")

  def __add__(self, other):
        return self.base_price * (1 + self.perc / 100) + other.base_price * (1 + other.perc / 100)
class iPhone12(AppleProduct):
  def __init__(self,name,model,ram,chip,perc,x=799):
    super().__init__(name,model,x)
    self.ram = ram
    self.chip = chip
    self.perc = perc
    self.base_price = 799
  def __str__(self):
    s = super().feature()
    s+= f"\nRAM: {self.ram}GB"
    s+=f"\nChip: {self.chip}"
    s+= f"{super().companyInfo()}"
    return s
  def calculatePrice(self):
    print("Calculating Price")
    print(f"{super().calculatePrice()}\nTax: {self.perc}%\nTotal Price: {self.base_price + self.base_price*(self.perc/100)}")
  def __add__(self, other):
        return self.base_price * (1 + self.perc / 100) + other.base_price * (1 + other.perc / 100)
m1 = MacBookPro2020('MacBook', 'MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8, 'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()
print('###################################')
print('Total Price of these two products: ',end='')
print('%.2f Dollars'%(m1 + iphone))

Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: M1
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Price
Base price: 1299
Tax: 10%
Total Price: 1428.9
###################################
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: A14Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Price
Total Price: 799
None
Tax: 5%
Total Price: 838.95
###################################
Total Price of these two products: 2267.85 Dollars

In [18]:
#Task-13
class University:
  name = "ABC University"
  numberOfStudents = 0
  admissionFee = 28000
  Library = 2000
  def __init__(self,n,i):
    self.stName = n
    self.stId = i
  def payment(self):
    return self.admissionFee+self.Library
  def __str__(self):
    return "Student Name: {}, ID: {}\nFee: {}".format(self.stName,self.stId,self.payment())

class CSE_dept(University):
  PerCreditFee = 6600
  SemesterFee = 7700
  LabFee = 2750
  def __init__(self,name,id,credit=6):
    super().__init__(name,id)
    University.numberOfStudents+=1
    self.credit = credit
  def __str__(self):
    s = (self.credit*self.PerCreditFee)
    s+=(super().payment()+self.SemesterFee+self.LabFee)
    return f"Student Name: {self.stName}, ID: {self.stId}\nFee: {s}"
  def __add__(self,other):
    if isinstance(other,CSE_dept):
      return (super().payment()+self.SemesterFee+(self.PerCreditFee*self.credit)+self.LabFee)+(other.admissionFee+other.Library+other.SemesterFee+(other.PerCreditFee*other.credit)+other.LabFee)
  def payment_details(self):
    print("DETAILS")
    print(f"Admission Fee: {self.admissionFee}\nLibrary Fee: {self.Library}")
    print(f"Semester Fee: {self.SemesterFee}\nPer Credit Fee: {self.PerCreditFee}")
    print(f"Number of credits: {self.credit}\nLab Fee: {self.LabFee}")

class PHR_dept(University):
  PerCreditFee = 6600
  SemesterFee = 11000
  def __init__(self,name,id,credit=9):
    super().__init__(name,id)
    University.numberOfStudents+=1
    self.credit = credit
  def __str__(self):
    s = (self.credit*self.PerCreditFee)
    s+=(super().payment()+self.SemesterFee)
    return f"Student Name: {self.stName}, ID: {self.stId}\nFee: {s}"
  def __add__(self,other):
    if isinstance(other,PHR_dept):
      return (super().payment()+self.SemesterFee+(self.PerCreditFee*self.credit))+(other.admissionFee+other.Library+other.SemesterFee+(other.PerCreditFee*other.credit))
  def payment_details(self):
    print("DETAILS")
    print(f"Admission Fee: {self.admissionFee}\nLibrary Fee: {self.Library}")
    print(f"Semester Fee: {self.SemesterFee}\nPer Credit Fee: {self.PerCreditFee}")
    print(f"Number of credits: {self.credit}")

c1 = CSE_dept("Mary","5678")
print(c1)
c1.payment_details()
print("===========================")
p1 = PHR_dept("Simon","91011")
print(p1)
p1.payment_details()
print("===========================")
c2 = CSE_dept("Adam","1234", 12)
print(c2)
c2.payment_details()
print("===========================")
p2 = PHR_dept("David","121314", 15)
print(p2)
p2.payment_details()
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))
print("===========================")
print("Due to the pandemic, admission and library fees have been reduced for all departments. ")
University.admissionFee -= 1000
University.Library -= 100
print("The credit, semester and lab fees have been reduced for the CSE department. ")
CSE_dept.PerCreditFee -= 100
CSE_dept.SemesterFee -= 100
CSE_dept.LabFee -=100
print("The credit and semester fees have been reduced for the PHR department.\n ")
PHR_dept.PerCreditFee -= 100
PHR_dept.SemesterFee -= 1000
print(c1)
print(p1)
print(c2)
print(p2)
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))

Student Name: Mary, ID: 5678
Fee: 80050
DETAILS
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 6
Lab Fee: 2750
===========================
Student Name: Simon, ID: 91011
Fee: 100400
DETAILS
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 9
===========================
Student Name: Adam, ID: 1234
Fee: 119650
DETAILS
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 12
Lab Fee: 2750
===========================
Student Name: David, ID: 121314
Fee: 140000
DETAILS
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 15
===========================
Total Number of Students: 4
Total University Revenue: 440100
===========================
Due to the pandemic, admission and library fees have been reduced for all departments.
The credit, semester and lab fees have been reduced for the CSE department.
The credit and semester fees have been reduced for the PHR department.

Student Name: Mary, ID: 5678
Fee: 78150
Student Name: Simon, ID: 91011
Fee: 97400
Student Name: Adam, ID: 1234
Fee: 117150
Student Name: David, ID: 121314
Fee: 136400
===========================
Total Number of Students: 4
Total University Revenue: 429100

In [29]:
#Task-14
class Library:
    Total_book = 1000
    borrow_data = {}

    def __init__(self,n,id):
        self.student_name = n
        self.student_id = id

    def borrowbook(self):
        print("A book is borrowed!")

    def __str__(self):
        return "Library: XYZ"
class Student(Library):
  def borrowbook(self,*args):
    if len(args)==2:
      if args[0] not in Library.borrow_data:
        Library.borrow_data[args[0]] = [self.student_name]
        Library.Total_book-=1
        super().borrowbook()
        print(f"{args[0]} book with the unique id {args[1]} is borrowed by {self.student_name}({self.student_id})")
        print(f"Number of books available for borrowing = {Library.Total_book}")
      else:
        print(f"Sorry {self.student_name}! {args[0]} is borrowed by {Library.borrow_data[args[0]][0]}")
    else:
      if args[0] not in Library.borrow_data:
        Library.borrow_data[args[0]] = [self.student_name]
        Library.Total_book-=1
        super().borrowbook()
        print(f"{args[0]}' book is borrowed by {self.student_name}({self.student_id})")

      print(f"Number of books available for borrowing = {Library.Total_book}")
  def __str__(self):
    s = super().__str__()
    s+= f"\nStudent Name: {self.student_name} ID: {self.student_id}"
    s+= "\nBooks borrowed: "
    for key,value in Library.borrow_data.items():
      if self.student_name in value[0]:
        s+=key + ","
    return s[:-1]
  def returnAllBooks(self):
    borrow = Library.borrow_data.copy()
    for key,value in borrow.items():
      if self.student_name in value[0]:
        del Library.borrow_data[key]
    print(f"All Books are returned by {self.student_name}")
s1 = Student("Alice",18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2= Student("David",18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

A book is borrowed!
The Alchemist book with the unique id Hdw652 is borrowed by Alice(18101259)
Number of books available for borrowing = 999
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: The Alchemist
===============
{'The Alchemist': ['Alice']}
===============
A book is borrowed!
Wuthering Heights' book is borrowed by Alice(18101259)
Number of books available for borrowing = 998
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: The Alchemist,Wuthering Heights
===============
Sorry David! The Alchemist is borrowed by Alice
===============
A book is borrowed!
The Vampyre' book is borrowed by David(18141777)
Number of books available for borrowing = 997
===============
{'The Alchemist': ['Alice'], 'Wuthering Heights': ['Alice'], 'The Vampyre': ['David']}
===============
All Books are returned by Alice
===============
{'The Vampyre': ['David']}

In [32]:
#Task-15
class Player:
    database = {}
    playerNo = 0
    def __init__(self, name, team, jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)
class FootballPlayer(Player):
  def __init__(self,name,team,jno,goal,date = "Not yet retired"):
    super().__init__(name,team,jno)
    Player.playerNo+=1
    self.goal = goal
    self.date = date
    self.x = ""
    for i in range(len(name)):
      if name[i] ==" ":
        self.x+=str(Player.playerNo)+name[0]+name[i+1]+str(jno)
    Player.database[self.x] = [name,team,jno,goal,date]
  @classmethod
  def createPlayer(cls,name,team,jno,goal,date):
    obj = cls(name,team,jno,goal,date)
    return obj
  def __str__(self):
    return f"Player ID: {self.x}\nName:{self.name}\nTeam:{self.team}\nJersey No:{self.jerseyNo}\nGoals Scored:{self.goal}\nRetirement date:{self.date}"
print("Number of players:", Player.playerNo)
print("Player Database:", Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11, 71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID: 1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals Scored:231
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals Scored:215
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals Scored:71
Retirement date:11 Aug,2014
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}

In [38]:
#Task-16
class Magical_SportsPerson:
    database = {}
    playerNo = 0
    def __init__(self,name,team,jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo

    def __str__(self):
     return "Name:{}\nTeam:{}\nJerseyNo:{}".format(self.name,self.team, self.jerseyNo)
class Quidditch_Player(Magical_SportsPerson):
  def __init__(self,name,team,jno,goal,date="Not yet retired"):
    super().__init__(name,team,jno)
    Magical_SportsPerson.playerNo+=1
    self.goal = goal
    self.date = date
    self.x = ""
    for i in range(len(name)):
      if name[i] ==" ":
        self.x+=str(Magical_SportsPerson.playerNo)+name[0]+name[i+1]+str(jno)
    Magical_SportsPerson.database[self.x] = [name,team,jno,goal,date]
  @classmethod
  def createPlayer(cls,name,team,jno,goal,date):
    obj = cls(name,team,jno,goal,date)
    return obj
  def __str__(self):
    return f"Player ID: {self.x}\nName:{self.name}\nTeam:{self.team}\nJersey No:{self.jerseyNo}\nGoals Scored:{self.goal}\nRetirement date:{self.date}"
print("Number of players:",Magical_SportsPerson.playerNo)
print("Player Database:",Magical_SportsPerson.database)
print("#################################")
p1 = Quidditch_Player("Harry Potter","Gryffindor", 8, 523)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = Quidditch_Player("Ronald Weasley","Gryffindor", 13, 5)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = Quidditch_Player.createPlayer("George Weasley","Gryffindor", 12, 11, "11 Magical Year, 1886")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Magical_SportsPerson.playerNo)
print("Player Database:",Magical_SportsPerson.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID: 1HP8
Name:Harry Potter
Team:Gryffindor
Jersey No:8
Goals Scored:523
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 2RW13
Name:Ronald Weasley
Team:Gryffindor
Jersey No:13
Goals Scored:5
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 3GW12
Name:George Weasley
Team:Gryffindor
Jersey No:12
Goals Scored:11
Retirement date:11 Magical Year, 1886
#################################
Number of players: 3
Player Database: {'1HP8': ['Harry Potter', 'Gryffindor', 8, 523, 'Not yet retired'], '2RW13': ['Ronald Weasley', 'Gryffindor', 13, 5, 'Not yet retired'], '3GW12': ['George Weasley', 'Gryffindor', 12, 11, '11 Magical Year, 1886']}

In [120]:
#Task-17
class User:
  def __init__(self,name,place,typ = "Single"):
    self.name = name
    self.place = place
    self.typ = typ
    self.green = False
    self.car = ""
  def status(self):
    if self.green == False:
      print(f"Status: {self.name} is looking for a {self.typ} ride!")
    else:
      print(f"Status: {self.name} boarded in car {self.car}")
class Uber:
  def __init__(self,*args):
    self.a_dict = {}
    for i in range(len(args)-1):
      key = args[i]+args[i+1]
      value = list(args[i+2:])
      self.a_dict[key] = value
      break

  def details(self):
    for key,value in self.a_dict.items():
      print(f"Car number: {key[:6]}")
      print(f"Type: {key[6:]}")
      x = " --> ".join(value)
      print(f"Routes: {x}")
  def pick(self,*args):
    for i in args:
     for key,value in self.a_dict.items():
      if i.place not in value:
        print(f"{i.name} destination is different from this car's route. ")
      elif i.place not in value[0:2]:
        print(f"{i.name} is looking for a different ride.")
      elif i.place in value and i.typ == "Single":
        print(f"{i.name} has been picked up.")
        i.green = True
        i.car = key[:6]
      else:
        print(f"{i.name} has been picked up.")
        i.green = True
        i.car = key[:6]



user1 = User("Brooks", "Banani", "Shared")
user2 = User("Jocelyn", "Uttara")
user3 = User("Robert", "Gulshan", "Shared")
user4 = User("Langdon", "Mohakhali", "Shared")


user1.status()
user2.status()
user3.status()
user4.status()
print("----------------------------------")
car1 = Uber("0K32BH", "Shared", "Mohakhali", "Banani", "Nikunja", "Uttara")
car1.details()
print("----------------------------------")
car1.pick(user1,user2,user3,user4)
print("----------------------------------")
user1.status()
user2.status()
user3.status()
user4.status()
print("----------------------------------")
car2 = Uber("5GD2BD", "Single", "Uttara")
car3 = Uber("4T12FR", "Shared", "Gulshan", "Bashundhara")
car2.details()
car3.details()
print("----------------------------------")
car2.pick(user2, user3)
print("----------------------------------")
car3.pick(user3)
print("----------------------------------")
user2.status()
user3.status()

Status: Brooks is looking for a Shared ride!
Status: Jocelyn is looking for a Single ride!
Status: Robert is looking for a Shared ride!
Status: Langdon is looking for a Shared ride!
----------------------------------
Car number: 0K32BH
Type: Shared
Routes: Mohakhali --> Banani --> Nikunja --> Uttara
----------------------------------
Brooks has been picked up.
Jocelyn is looking for a different ride.
Robert destination is different from this car's route.
Langdon has been picked up.
----------------------------------
Status: Brooks boarded in car 0K32BH
Status: Jocelyn is looking for a Single ride!
Status: Robert is looking for a Shared ride!
Status: Langdon boarded in car 0K32BH
----------------------------------
Car number: 5GD2BD
Type: Single
Routes: Uttara
Car number: 4T12FR
Type: Shared
Routes: Gulshan --> Bashundhara
----------------------------------
Jocelyn has been picked up.
Robert destination is different from this car's route.
----------------------------------
Robert has been picked up.
----------------------------------
Status: Jocelyn boarded in car 5GD2BD
Status: Robert boarded in car 4T12FR